### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by delvedor** [fastify/light-my-request#1]
- [x] explain why we forked the original project
- [x] ~~MIT license~~
- [x] fix Node v8
- [x] Promises support

cc @mcollina

**Comment by jsumners** [comment]
Can the license be changed at will like that?

**Comment by delvedor** [comment]
As far as I know yes, if I'm wrong please correct me! :)

The previous license was `BSD-3-Clause`, which says that we must keep the contributors list and the disclaimer.
You can find the contributors at the end of our [README.md](https://github.com/fastify/light-my-request#acknowledgements) file, as well as the previous license, while the disclaimer is inside the [LICENSE](https://github.com/fastify/light-my-request/blob/master/LICENSE).

**Comment by delvedor** [comment]
Ops, apparently I was wrong, we should keep the `BSD-3-Clause` and update the copyrights.
I'm sorry, I'm not an expert in licensing and legal stuff :P
Thank you for pointing out!

**Comment by jsumners** [comment]
By no means am I a lawyer, but it seems to me the original license said that any redistribution must retain that license. The following seems to concur that you can't change the license without major changes to the codebase:

+ https://softwareengineering.stackexchange.com/questions/240612/forking-bsd-project-and-changing-license
+ https://softwareengineering.stackexchange.com/a/75459/34330

**Comment by delvedor** [comment]
Done in https://github.com/fastify/light-my-request/commit/a4c7f80e13c49d20f730a5da06f01897cb1a7401.
