### ISSUE TITLE
handle errors emitted through connection.destroy()

### ISSUE THREAD

**Issue by mcollina** [fastify/light-my-request#10]
Unfortunately the current interface does not allow us from surfacing those errors.

I propose that we change:

1. from `inject(data, callback(res))` to `inject(data, callback(err, res))`
2. from `inject(data).then(res)` to `inject(data).catch().then()`.

**Comment by delvedor** [comment]
Agree.
I'll work on this.

**Comment by delvedor** [comment]
Closed in #11
