### ISSUE TITLE
An option to make the callback function called at the beginning of stream response

### ISSUE THREAD

**Issue by BlackGlory** [fastify/light-my-request#105]
## 🚀 Feature Proposal

I noticed that `light-my-request` seems impossible to test stream responses (e.g. Server-Sent Events).

If there is an option that invoke callback at the beginning of the response, it is possible to test the stream data through `res.raw`.

## Motivation

To test stream responses.

## Example

Maybe
```js
inject(dispatch, { method: 'get', url: '/', stream: true }, (err, res) => {
  console.log(res.raw)
})
```

**Comment by mcollina** [comment]
Unfortunately SSE (and websockets) are not currently supported. It would be a good feature to add, would you like to work on it?

**Comment by BlackGlory** [comment]
I finally chose to start the server for integration testing.

I realized there are already modules such as `node-fetch` and `eventsource`, so the test will be closer to the real scene. `light-my-request` does not seem to be necessary.

It is easy to encounter [this problem](https://github.com/fastify/fastify/issues/2037) in integration testing, and it is difficult to debug effectively. fastify may need to provide a method to force close the server.

**Comment by mcollina** [comment]
> It is easy to encounter this problem in integration testing, and it is difficult to debug effectively. fastify may need to provide a method to force the server shutdown.

Please report a reproducible issue with an example.

**Comment by BlackGlory** [comment]
I don't want to create a repo for this, so I just paste here.

`index.js`
```js
const fastify = require('fastify')

exports.buildServer = () => {
  const server = fastify()

  server.get('/', (req, reply) => {
    ;(async () => {
      reply.raw.setHeader('Content-Type','text/event-stream')
      reply.raw.setHeader('Connection', 'keep-alive')
      reply.raw.setHeader('Cache-Control', 'no-store')
      reply.raw.flushHeaders()
      for (let i = 100; i--; ) reply.raw.write(`data: ${i}\n\n`)
    })()
  })

  return server
}
```

`__tests__/test.spec.js`(jest)
```js
const EventSource = require('eventsource')
const { buildServer } = require('../index.js')

test('timeout', async () => {
  const server = buildServer()
  const address = await server.listen(0)

  try {
    const es = new EventSource(address)
    await waitForEvent(es, 'open')
    console.log('proof')
  } finally {
    // server.close() will never be resolved.
    await server.close()
  }
})

test('not timeout', async () => {
  const server = buildServer()
  const address = await server.listen(0)

  try {
    const es = new EventSource(address)
    await waitForEvent(es, 'open')
    console.log('proof')
    es.close() // The key difference
  } finally {
    await server.close()
  }
})

function waitForEvent(target, event) {
  return new Promise(resolve =>
    target.addEventListener(event, x => resolve(x.target), { once: true })
  )
}
```

The expected result is that `server.close()` will forcefully kill the SSE connection, but it not.
