### ISSUE TITLE
Remove ajv from dependancies

### ISSUE THREAD

**Issue by Eomm** [fastify/light-my-request#151]
Thanks to ajv 8, it is possible to avoid the `compile` call building the schema with the standalone feature.

https://github.com/fastify/light-my-request/blob/4654762628afaa2d135e560e9a1cde05d3a6f5f7/index.js#L68

In this way, it is possible to move the ajv dependency to the devDependancies and provide a faster initialization of this module and a smaller package.

Doing so, could be a minor semver feature since the compiled code is node.js 10 compatible.

**Comment by mcollina** [comment]
Last time I checked that still required a runtime dependency on ajv for some utility functions... has that changed?

**Comment by zekth** [comment]
Faster initialization but slower execution isn't it?

**Comment by Eomm** [comment]
It depends on the schema that is being compiled. We need to generate the functions and checkout the generated code

**Comment by mcollina** [comment]
I'll close this and we'll reevaluate when Ajv ships fully independent compilation.
