### ISSUE TITLE
Error: res.getHeader is not a function (incorrect TypeScript types)

### ISSUE THREAD

**Issue by limulus** [fastify/light-my-request#176]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.0

### Node.js version

16.13.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.1

### Description

The TypeScript types for light-my-request indicate there should be a `getHeader()` method on the `LightMyRequest.Response` object, because the types indicate it inherits from `http.ServerResponse` which has this method. However, it appears that it does not include `http.ServerResponse` in the inheritance chain.

Thanks for taking a look at this!

### Steps to Reproduce

The following code is valid according to the TypeScript types:

```typescript
import fastify from 'fastify'

async function main() {
  const server = fastify()
  const res = await server.inject().get('/')
  res.getHeader('host')
}

main()
```

However, running the generated JavaScript produces the following error:

```
test.js:8
    res.getHeader('host');
        ^

TypeError: res.getHeader is not a function
    at main (test.js:8:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

Either TypeScript should produce an error to indicate the code is incorrect, or it should run without error.

**Comment by climba03003** [comment]
It is not related to `light-my-request`.
`light-my-request` is inheriting the proper `http.ServerResponse`.
https://github.com/fastify/light-my-request/blob/4b28c4bb1f3e32879fe79a65b6aa7e67595e25e0/lib/response.js#L10-L14

But, it is not the case for using it inside `fastify`. `fastify` provide it's own `Response`.

**Comment by climba03003** [comment]
I about check the code and see the problem.
https://github.com/fastify/light-my-request/blob/4b28c4bb1f3e32879fe79a65b6aa7e67595e25e0/lib/response.js#L115-L151

**Comment by valenfv** [comment]
Hello everyone! Do we want to extend from `http.ServerResponse`?

**Comment by mcollina** [comment]
> Hello everyone! Do we want to extend from `http.ServerResponse`?

We already are: https://github.com/fastify/light-my-request/blob/master/index.d.ts#L74

**Comment by limulus** [comment]
Hi @mcollina! So that’s true in the handcrafted `.d.ts`, but it does not seem to be true in the actual JS (if I am understanding it correctly): https://github.com/fastify/light-my-request/blob/master/lib/request.js#L127

**Comment by mcollina** [comment]
would you like to send a PR for that?

**Comment by limulus** [comment]
Sure! I’ve gone ahead and submitted #177.

After getting an understanding of the code, it seemed like it might be problematic to make `Response` truly inherit from `http.ServerResponse`. So instead I split the `Response` type into two types:

  - For the response object that gets returned by `inject()`, that type continues to be called `Response`, but no longer inherits from `http.ServerResponse`
  - For the response object passed to the dispatch function, that type got renamed to `ServerResponse`, and it simply extends `http.ServerResponse`

Thanks for taking a look!
