### ISSUE TITLE
.inject simulate options doesn't work

### ISSUE THREAD

**Issue by igorwessel** [fastify/light-my-request#184]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Node.js version

14.18.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

The options to simulate some events in the request, doesn't work as it should.

e.g:
```js
inject({
    url: "/hello",
    simulate: {
      close: false,
      split: false,
      end: true,
      error: true
    }
})
```

The request happens normally but it should return some kind of error.

### Steps to Reproduce

Run tests in another terminal with
```bash
yarn test
``` 

https://codesandbox.io/s/reverent-architecture-iec1qu?file=/package.json

### Expected Behavior

From what I understand from the Fastify documentation it should probably return an object of the type
```js
{
	statusCode: number,
	error: string,
	message: 'Simulated'
}
```

I'm not sure how should return because it's my first time trying to use this option to simulate.

**Comment by kibertoad** [comment]
Have you tried using newer fastify? rc1 seems ancient.

**Comment by igorwessel** [comment]
> Have you tried using newer fastify? rc1 seems ancient.

I ended up making this sandbox through fastify-starter template and I didn't notice that it was so outdated, but in my personal project which uses ***fastify: 3.27.3*** occurs the same problem.

I updated the sandbox project to use the latest version of fastify.

**Comment by climba03003** [comment]
I think `fastify` do not add any event listener (e.g. `error`, `close`.) to the `request` object. So, the simulation in here will not work.
Not sure if it is intended not to handle those event by default.

**Comment by igorwessel** [comment]
> I think `fastify` do not add any event listener (e.g. `error`, `close`.) to the `request` object. So, the simulation in here will not work. Not sure if it is intended not to handle those event by default.

I thought fastify with any exception would become an error for it to handle.

**Comment by Eomm** [comment]
> The request happens normally but it should return some kind of error.

The `simulate` acts based on the stream between client and server.
So the error event is emitted when the server tries to read the request payload (because when the server receives a request, the headers and the URL has been already transmitted).

Here a working example:

```
const fastify = require('fastify')({ logger: false })
fastify.post('/hello', async (request, reply) => {
  return 'asd'
})

fastify.setErrorHandler(function (error, request, reply) {
  this.log.error(error)
  reply.status(500).send({ ok: false })
})

fastify
  .inject({
    url: '/hello',
    method: 'POST',
    payload: 'a'.repeat(100000),
    simulate: {
      error: true,
    },
  })
  .then((response) => {
    console.log(response.payload)
  })
  .catch((err) => {
    console.log({ err })
  })

```

Please, reach out to the source code or the tests for more insight into this feature
