### ISSUE TITLE
Cookie support?

### ISSUE THREAD

**Issue by ianwalter** [fastify/light-my-request#19]
I'm interested in this so I can simulate requests that require a session cookie. Thoughts?

**Comment by delvedor** [comment]
By default we do not provide any api to interact with cookies, but you can work with cookie headers.
On the server side you just need to use [`fastify-cookie`](https://github.com/fastify/fastify-cookie)

**Comment by ianwalter** [comment]
Yes, I guess an explicit api is not really necessary. Thanks for your reply.
