### ISSUE TITLE
Response.json() return error without header

### ISSUE THREAD

**Issue by leandroandrade** [fastify/light-my-request#193]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

>=3.0.0

### Plugin version

5.x.x

### Node.js version

16.14.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3.1 

### Description

Response.json() throws an error when the does not exist payload. This is common when we have an empty response like using http code 201 or 204.

### Steps to Reproduce

Add this test case and the error will be printed.

```
test('Response.json() should return undefined if the payload does not exist', (t) => {
    t.plan(2)
  
    const dispatch = function (req, res) {
      res.writeHead(204)
      res.end()
    }
  
    inject(dispatch, { method: 'GET', path: 'http://example.com:8080/hello' }, (err, res) => {
      t.error(err)
      const { json } = res
      t.equal(json(), undefined)
    })
  })
```

### Expected Behavior

I'd expect this to return an undefined, not an error.

**Comment by mcollina** [comment]
Why would expect it to return `undefined`? It seems returning an Error is correct.

**Comment by leandroandrade** [comment]
Because throwing an error apparently is not a behavior expected. The code does not have an error, we just have not passed a payload. 

Return an ```undefined``` when not exists a payload show something more expected.

**Comment by mcollina** [comment]
Unfortunately that's not the case.  Your route did not return a valid
JSON document (a JSON document is at least 2 bytes), therefore I would expect an error. We can argue about a _better_ error message, but if you are trying to parse something as JSON that is not JSON, you expect to receive an error.
