### ISSUE TITLE
Implement an Axios Adapter

### ISSUE THREAD

**Issue by segevfiner** [fastify/light-my-request#199]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

An interesting use case can be to be able to plug light-my-request as an Axios adapter so you can use an existing HTTP REST client instead of hand crafting requests.

### Motivation

We have a generated Axios HTTP client and a Fastify Server which wraps up `light-my-request` under it with an `inject` method. It would be nice to be able to use the Axios client and point it to the Fastify server's `light-my-request` so we don't have to hand-craft requests for testing.

### Example

```ts
const client = new Client({ baseOptions: { adapter: new LightMyRequestAdapter(server) }}); // Where client accepts Axios instance options under baseOptions
client.helloWorld();
```

**Comment by segevfiner** [comment]
Yeah. Should I do so, I will post it here.

**Comment by segevfiner** [comment]
Meh... The adapter interface of Axios isn't factored out that well, the existing adapters depend on a lot of unexported utilities and do a lot of Axios specific processing rather than only handling actually sending the request. This is proving more difficult then I thought it would be... Also, they support cancellation, which light-my-request doesn't.

**Comment by mcollina** [comment]
Nice one! You  might want to write some unit tests and then create a Fastify plugin that wraps it for usage with Fastify!

**Comment by segevfiner** [comment]
That's the idea. 👍 Though I thought about a standalone function, or an example, for a start. I wonder how can I build a Fastify plugin for this, as in, what should its interface be? What should I decorate the server with? I need to get Fastify's `dispatchFunc` which I guess is exposed via `server.routing` or `server.listeners('request')`, and there is this part in Fastify's own inject that I'm not sure if I should or how to replicate as those are private props: https://github.com/fastify/fastify/blob/d45bcb6b3a3cb412a7b7799a34fe34867f1df854/fastify.js#L470-L482

**Comment by mcollina** [comment]
You wouldn't be able to replicate that functionality, your decorator would be available only after `fastify.ready()` has resolved.

**Comment by segevfiner** [comment]
Yeah, that's assuming I expose it as a Fastify plugin, it can probably only check the closed condition, but that's not exposed either AFAIK.

**Comment by segevfiner** [comment]
https://github.com/segevfiner/axios-light-my-request-adapter is available and a bit more tested now. Hopefully it works for anyone else who wants this.
