### ISSUE TITLE
Support cancellation via `.destroy()` and `AbortSignal`, and setting a timeout

### ISSUE THREAD

**Issue by segevfiner** [fastify/light-my-request#203]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be nice to support a way to cancel the request via a `.destroy()` method and/or an `AbortSignal` like the plain Node.js `http.request`, and also setting a timeout with a similar interface to `http.request` or something more suitable for light-my-request.

### Motivation

https://github.com/segevfiner/axios-light-my-request-adapter

### Example

```js
const controller = new AbortController();
const req = inject(/* ... */, {signal: controller.signal, timeout: 1000});
controller.abort();
const res = await req;
```

**Comment by mcollina** [comment]
I have absolutely no idea how this could be implemented. HTTP is not canceleable.

**Comment by segevfiner** [comment]
It's essentially closing the connection, simulating a client disconnect. That's what `ClientRequeat.destroy` or using an `AbortController` with it does.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by piotr-cz** [comment]
Sadly, this doesn't work when server response is a stream.

Executing `controller.abort()` throws an `AbortError: The operation was aborted` within Fastify lib
