### ISSUE TITLE
query is typed as string | { [k: string]: string | string[] } but passing a string doesn't work

### ISSUE THREAD

**Issue by segevfiner** [fastify/light-my-request#204]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

N/A (light-my-request 5.0.0)

### Node.js version

16.16.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 10.0.19044.0 x64

### Description

query is typed as `string | { [k: string]: string | string[] }` but passing a `string` doesn't work, it gets treated as an object and produces a broken query string.

### Steps to Reproduce

1. Pass a string to `url.query`, `path.query` or `query`.

### Expected Behavior

A string gets treated as a verbatim query string.

**Comment by Eomm** [comment]
Thanks for reporting!
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by segevfiner** [comment]
Do we want to add support for `string` or remove that from the types?

**Comment by mcollina** [comment]
I think we can support passing a query that's a string
