### ISSUE TITLE
It is necessary that the headers: user-agent and content-type could not be filled in automatically when setting the flag in the settings

### ISSUE THREAD

**Issue by budarin** [fastify/light-my-request#214]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Many tools, such as `curl`, do not automatically fill in these parameters, so during testing of services it is necessary to disable the automatic filling of these headers in order to test the response of the service to their absence.

```
curl -X POST http://localhost:3000/route --body "{}"
```

I suggest adding a parameter to the settings that would regulate this behavior

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by budarin** [comment]
I'll try
