### ISSUE TITLE
Dispatch function Request.body is undefined

### ISSUE THREAD

**Issue by flipperlite** [fastify/light-my-request#242]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.12.0

### Plugin version

5.9.1

### Node.js version

18.14.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Version 13.2.1 (22D68)

### Description

I have middleware that I'm testing that validates the request.body via [AJV](https://github.com/ajv-validator/ajv). It's checking query string and body parameters against a known schema.  I'm trying to setup my routes like [this example](https://github.com/wolfejw86/blog-examples/blob/master/fastify-jest-example/src/routes/root.ts). Its jest tests use your plugin behind the scenes like [this example](https://github.com/wolfejw86/blog-examples/blob/master/fastify-jest-example/test/routes/root.test.ts). For whatever reason, the dispatch or plugin function has no handle to the request.body when the body object is passed in as the payload. With request.body being undefined, I'm unable to confirm my middleware is validating the body parameters.

I cloned your repo and simply put in a console.log where I thought it would be in [this file](https://github.com/fastify/light-my-request/blob/master/test/index.test.js#L595). See the console.log that I added.

```javascript
test('supports body option in Request and property in Response', (t) => {
  t.plan(3)
  const dispatch = function (req, res) {
    console.log('req.body', req.body) // it's undefined making it impossible to test middleware functions
    res.writeHead(200, { 'content-type': req.headers['content-type'] })
    req.pipe(res)
  }

  inject(dispatch, { method: 'POST', url: '/test', body: { a: 1 } }, (err, res) => {
    t.error(err)
    t.equal(res.headers['content-type'], 'application/json')
    t.equal(res.body, '{"a":1}')
  })
})
```

I expected req.body to be populated with the injected body: { a: 1 } but it's undefined.

### Steps to Reproduce

Add the following line:

```javascript
console.log('req.body', req.body) // it's undefined making it impossible to test middleware functions
```

at line 595 of https://github.com/fastify/light-my-request/blob/master/test/index.test.js#L595

### Expected Behavior

The request body (req.body) in the code examples to be populated with the injected body object { a: 1 } but it's undefined.

**Comment by Eomm** [comment]
You must read it. `req.body` is something that is handled by Fastify to make HTTP simple

This module is more at a lower level interface

```
const http = require('http')
const inject = require('light-my-request')

const dispatch = function (req, res) {
  const reply = 'Hello World'
  
  const chunks = []
  req.on('data', (chunk) => {
    chunks.push(chunk)
  })
  req.on('end', () => {
    console.log(Buffer.concat(chunks).toString())
    res.writeHead(200, { 'Content-Type': 'text/plain', 'Content-Length': 'bye bye'.length })
    res.end('bye bye')
  })
}

const server = http.createServer(dispatch)

inject(dispatch, { method: 'get', url: '/', body: {foo:'bar'} }, (err, res) => {
  console.log(res.payload)
})
```

**Comment by flipperlite** [comment]
@Eomm thank you for the quick response. I'd argue that the req.body needs to be populated as I'd expect Fastify to populate in middleware without extra code. Why else would you use `light-my-request` then? It doesn't make sense to me why I'd want the reply.body populated in your unit test but not have req.body populated where the business logic would be. Here's an easy solution that you could put into the base code.

```javascript
test('supports body option natively in Request', (t) => {
  t.plan(3)
  const dispatch = function (req, res) {
    res.writeHead(200, { 'content-type': req.headers['content-type'] })
    res.end(JSON.stringify(req.body))
  }

  inject(setReqBody(dispatch), { method: 'POST', url: '/test', body: { a: 1 } }, (err, res) => {
    t.error(err)
    t.equal(res.headers['content-type'], 'application/json')
    t.equal(res.payload, '{"a":1}')
  })
})

function setReqBody (fn) {
  return (req, res) => {
    const chunks = []
    req.on('data', (chunk) => {
      chunks.push(chunk)
    })
    req.on('end', () => {
      req.body = JSON.parse(Buffer.concat(chunks).toString())
      return fn(req, res)
    })
  }
}
```
