### ISSUE TITLE
Headers with value set to null are wrongly emitted as string in the response 

### ISSUE THREAD

**Issue by ericmorand** [fastify/light-my-request#249]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.18.0

### Plugin version

5.10.0

### Node.js version

16.x and above

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Our test suite, based on the test application provided by fastify, is suddenly failing even though we did not change fastify version.

This is likely because of this change:

https://github.com/fastify/light-my-request/commit/23f4fa06d0748448e045bfb28f500959f1550a49

Before, setting a response header value to `null` in the route handler was successfully propagated as `null` in the response returned by fastify test application.

Now, setting a response header value to `null` in the route handler leads to the string "null" being propagated in the response returned by fastify test application. Making our test suite fails.

This is a breaking change: this library has always been supporting setting a header to `null`. It does not support it anymore.

### Steps to Reproduce

Just set a header value to `null` using the `header` or `headers` function of fastify response and check the value of the header in the response returned by the test application. It will be the string "null" instead of the `null` value.

**Comment by Uzlopak** [comment]
I actually expect, that `null` and `undefined` should result that the corresponding keys should not existing in the final object.

**Comment by mcollina** [comment]
I've reverted the fix to match Node.js core behavior:

```js
const { createServer, request } = require('http');

const server = createServer((req, res) => {
  res.setHeader('Content-Type', 'text/plain');

  try {
    res.setHeader('X-undefined', undefined);
  } catch (err) {
    console.log('undefined could not be set')
  }
  res.setHeader('X-null', null);
  res.end('Hello World!');
})

server.listen(3000, function () {
  console.log('Server listening on port 3000');
  request('http://localhost:3000', function (res) {
    console.log(res.headers);
    process.exit(0);
  }).end()
});
```
