### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by rdzar** [fastify/light-my-request#265]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.2

### Node.js version

20.8

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Latest

### Description

Whenever the Fastify endpoint returns 'invalid' JSON;
`.response.send(null)`

The Fastify endpoint still returns without throwing errors, but the `light-my-request` throws an error whenever handeling this kind of response.

```bash
Failed: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.parseJsonPayload [as json] (/node_modules/light-my-request/lib/response.js:143:17)
```

### Steps to Reproduce

1. Make a API endpoint in Fastify that returns `null` as response
```js
fastify.get('/test', async (request, reply) => {
  reply.type('application/json').code(200)
  reply.send(null);
  return reply;
})
```
2. Make request using `light-my-request` 
```js
await fastify.inject({
 'url': '/test',
 'method': 'GET'
});
```
3. Crash

### Expected Behavior

Expected the response to be empty, like the browser response of Fastify in this case
![image](https://github.com/fastify/light-my-request/assets/310687/bb26fb99-2597-4086-89f8-0980b1aa69d3)

**Comment by Eomm** [comment]
Can't replicate:

```
const run = async () => {
  const app = require("fastify")({ logger: !true });
  app.get("/", async (request, reply) => {
    reply.type("application/json").code(200);
    reply.send(null);
    return reply;
  });
  const res = await app.inject("/");
  console.log(res.payload);
};

run();
```

**Comment by rdzar** [comment]
Mmm, I tried everything to reproduce it in smaller code-base but I'm unable to. Somehow the JSON parse crashes, with the above stack-trace, but we're using a custom findMyWay router between these endpoints so its a bit tricky to make it smaller. 

My reproduction code is already 200 lines and I'm still unable to do so. Sorry I guess :)
