### ISSUE TITLE
Testing a streamed response using `light-my-request`?

### ISSUE THREAD

**Issue by Fdawgs** [fastify/light-my-request#283]
## 💬  Question here 

First off, finally got my company using Fastify, success!

Using [light-my-request](https://github.com/fastify/light-my-request), is it possible to see a streamed response's individual chunks?

Unfortunately, I can't provide an example due to it exposing too much internal info/workings but essentially I have a GET endpoint that returns a JSON-SEQ stream, with each chunk being a JSON Text Sequence, below is the test:
```js
    it('Returns a stream of JSON Text Sequence results', async () => {
      const response = await server.inject({
        method: 'GET',
        url: '/',
        query: {
          boop: 'test',
        },
        headers: {
          accept: '*/*',
        },
      })

      console.log(response.raw.res._lightMyRequest.payloadChunks)

      expect(response.headers).toMatchObject({
        'content-type': 'application/json-seq; charset=utf-8',
      })
      expect(response.statusCode).toBe(200)
     // expect(response.body).toBe('{"test": "I\'m a test"}\n')
    })
```

I can see the individual chunks are stored in an array of buffers inside `response.raw.res._lightMyRequest.payloadChunks` but obviously `_lightMyRequest` is intended to be private. Is there was a nicer way of getting at them?

## Your Environment

- *node version*: 18.\*, 20.\*
- *fastify version*: 4.26.1
- *light-my-request version*: 5.12.0
- *os*: Windows, Linux

**Comment by gurgunday** [comment]
> First off, finally got my company using Fastify, success!

This is amazing, congrats! 🚀
