### ISSUE TITLE
Missing 5.14.0 release

### ISSUE THREAD

**Issue by kudlav** [fastify/light-my-request#303]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

There is a new version [5.14.0](https://www.npmjs.com/package/light-my-request/v/5.14.0) on the NPM repository but version 5.14.0 is not mentioned here on the GitHub repository both in tags or releases.

Please add the 5.14.0 release or at least a tag. I'd like to know what's changed.

**Comment by Uzlopak** [comment]
done ;)

**Comment by Uzlopak** [comment]
also created v6.1.0
