### ISSUE TITLE
Question: How to upload a file?

### ISSUE THREAD

**Issue by cemremengu** [fastify/light-my-request#35]
I would like to upload `multipart/form-data` using inject. Currently, using [this plugin](https://github.com/huangang/fastify-file-upload#readme) to get the files but I am unable to do so. 

Is this possible?

**Comment by mcollina** [comment]
You should be able to use
https://github.com/form-data/form-data to do that

Il giorno mar 19 feb 2019 alle 21:48 Cemre Mengu <notifications@github.com>
ha scritto:

**Comment by cemremengu** [comment]
Thank you! Ended up with:

```js
  const FormData = require('form-data')
  const form = new FormData()
  form.append('myfile', fs.createReadStream(`./path/to/file`))

  const res = await app.inject({
    url: '/api/upload
    method: 'POST',
    payload: form,
    headers: form.getHeaders()
  });
```
