### ISSUE TITLE
Should check for `undefined`?

### ISSUE THREAD

**Issue by jsumners** [fastify/light-my-request#37]
Should this check for `undefined` as well as `false`?

https://github.com/fastify/light-my-request/blob/f06c85f5c3f3dc98ac9adc37d7d0c2ad1cc5824a/index.js#L62

**Comment by mcollina** [comment]
Likely. is this throwing for you? Can you add an example?

**Comment by jsumners** [comment]
I don't have a specific example. I just noticed it while stepping through code. Basically, whatever code I had was getting here with `options.validate = undefined` and going through the branch. I don't know what path should be taken in that case.
