### ISSUE TITLE
Provide RESTful and chainable apis to make things easier

### ISSUE THREAD

**Issue by fralonra** [fastify/light-my-request#50]
## 🚀 Feature Proposal

Give direct apis for every HTTP methods and others like `header` and `body`.

## Motivation

Currently we use properties in `options` object passed to `inject` to tell light-my-request what is the request url, what is the method, and some other things.

I think it would make coding simpler if we provide standalone apis for such things, and make them chainable. As a result, the `options` can be omitted, and the callback can be moved to the last method of the chain.

## Example

```js
const inject = require('light-my-request')

const dispatch = (req, res) => {
  // some code
}

inject(dispatch)
  .get('/test')
  .header({ foo: 'bar' })
  .end((err, res) => {
    // some debug code
  })

inject(dispatch)
  .post('/test')
  .body({ foo: 'bar' })
  .end((err, res) => {
    // some debug code
  })

// you can follow the old way as well
inject(dispatch, { method: 'get', url: '/test' }, (err, res) => {
    // some debug code
  })
```

**Comment by fralonra** [comment]
@mcollina 
Did you mean parse JSON in the request body? It's already handled by `body` and `payload`.

**Comment by fralonra** [comment]
To avoid messing up the original code, I decided to make another library that wraps `light-my-request` as a first step.

Here it is. [injectar](https://github.com/fralonra/injectar).

**Comment by mcollina** [comment]
Awesome work! I’m closing this then.
