### ISSUE TITLE
Typings: Response doesn't have addTrailers method

### ISSUE THREAD

**Issue by fralonra** [fastify/light-my-request#57]
## 🐛 Bug Report

In `index.d.ts`, the `Response` interface declares a method `addTrailers`, but it doesn't have this method indeed.

https://github.com/fastify/light-my-request/blob/master/index.d.ts#L79

**Comment by mcollina** [comment]
Would you like to send a PR?

Il giorno mar 15 ott 2019 alle 03:51 Zoron <notifications@github.com> ha
scritto:
