### ISSUE TITLE
inject cookie

### ISSUE THREAD

**Issue by Eomm** [fastify/light-my-request#71]
## 🚀 Feature Proposal

Add the feature to send a request with cookies and read the cookies in the response easily

## Motivation

Simplify the cookie usage

## Example

```js
inject(dispatch, { method: 'get', url: '/', cookies: {
 foo: 'bar'
} }, (err, res) => {
  console.log(res.payload)
  console.log(res.cookies()) // returned by the server (same usage of .json() feature)
})
```

**Comment by mcollina** [comment]
Definitely! Would you like to send a PR?
