### ISSUE TITLE
Type definition for Response.json() is inaccurate

### ISSUE THREAD

**Issue by robcresswell** [fastify/light-my-request#82]
## 🐛 Bug Report

The type definition for the Response interface has a `.json()` function, which returns `object`. `object` in TS is the same as `{}`, which is not what the json() response value is.

Personally I'd suggest using something like the `Json` example here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#more-recursive-type-aliases which is 

```ts
type Json =
    | string
    | number
    | boolean
    | null
    | { [property: string]: Json }
    | Json[];
```

Another option would be to copy Node's own `JSON.parse()` return which is `any`, or even to return `unknown`.

## To Reproduce

I personally stumbled across then when using `fastify.inject`, and then attempted to destructure a key from the `.json()` response.

```ts
const createResult = server.inject({ method: 'POST', url: '/create'});
const { id } = createResult.json();
```

This will error, as it "correctly" tells me that `id` is not an attribute on `{}`.

## Expected behavior

I'd expect this to be more correct, or at least more loosely typed. As it stands, its strict and wrong, I believe.

## Your Environment

- *node version*: 13
- *fastify version*: >=2.0.0
- *os*: Linux

**Comment by mcollina** [comment]
Would you like to send a PR to fix this?

**Comment by robcresswell** [comment]
Gladly! Do you have a preference on the solution? Changing it to `any` is probably the easiest from a maintainers point of view, and matches with the `JSON.parse()` return value IIRC.

**Comment by mcollina** [comment]
I’m totally fine with the result of JSON.parse()

**Comment by robcresswell** [comment]
PR here: 

https://github.com/fastify/light-my-request/pull/83
