### ISSUE TITLE
Missing socket

### ISSUE THREAD

**Issue by Eomm** [fastify/light-my-request#87]
Hi,
I'm writing some test for a Fastify plugin that uses some `koa` handler to manage routes.

The test is failing due this check of `koa` lib:

```
if (this.socket.encrypted) return 'https';
```
https://github.com/koajs/koa/blob/master/lib/request.js#L402

Considered that:
- the final solution would be to implement a native plugin for Fastify
- light my request says "**Does not use a socket connection**.."
- I can use `listen` instead of `inject` to write my tests

Do you think adding a `this.socket = {}` to the light-my-request is a bad idea?
How would you cover this use case?

**Comment by humphd** [comment]
I also need this to get tests passing for the change in https://github.com/fastify/fastify/issues/2575, switching from `.connection` to `.socket`.

I tried doing a naive switch in https://github.com/fastify/light-my-request/blob/b416dd64d97bf431fab14f7b19bf62edb15b757f/lib/request.js#L67-L69 from `this.connection = {...}` to `this.socket = {...}`, but it's clearly going to need more than that.

I also found that doing so broke other modules that depend on the `request` still having a `.connection` property (e.g., [forwarded](https://github.com/jshttp/forwarded/blob/master/index.js#L31)).

**Comment by mcollina** [comment]
You need add: `this.socket = this.connection` right after that block.

**Comment by humphd** [comment]
Thanks @mcollina, I'll do that and send a PR.
