### ISSUE TITLE
response body not being parsed automatically (and should be!)

### ISSUE THREAD

**Issue by mikemaccana** [fastify/light-my-request#94]
## 🚀 Feature Proposal

I'm not sure if this is a Feature Proposal or a bug report. But unlike normal Fastify (which parses request bodies automatically), response bodies don't seem to be parsed automatically when using `light-my-request` (via app.inject()`).

```
let response = await app.inject({
  method: "POST",
   url: `/someurl`,
   payload,
  });
let body = JSON.parse(response.payload).data;  
```
## Motivation

Every single time ` app.inject()` is used we have to decode the response. Decoding JSON when the Content-Type is JSON is a reasonable default used by most popular clients like superagent and axios, and also consistent with Fastify itself (Fastify routes decode request bodies). 

## Example

```
let response = await app.inject({
  method: "POST",
   url: `/someurl`,
   payload,
  });
console.log(response.body)
```
Thanks for reading!  🙂

**Comment by jsumners** [comment]
Fastify _encodes_ the response bodies. It is up to the client to decode them. In this case, the client is `light-my-request`. It does not have any concept of the intended usage of said response bodies so it does not decode them by default. In the case of JSON response bodies, you can `const myJSON = response.json()`.

**Comment by mcollina** [comment]
I'd be ok to add a `json: true` flag to `inject()` to automatically decode.

**Comment by mikemaccana** [comment]
> It is up to the client to decode them. In this case, the client is light-my-request.

Yep, that's why I'm filing this bug/feature request here. The only reason I mention Fastify is in terms of decoding request bodies, much like light-my-request does with response bodies.

>  It does not have any concept of the intended usage of said response bodies so it does not decode them by default. 

This is what `Content-Type: `header in HTTP responses does.

**Comment by mikemaccana** [comment]
@mcollina Brilliant! After we make it, could we set it to `true` by default in the next `light-my-request` release?

**Comment by mcollina** [comment]
> Brilliant! 😃 After we make it, could we set it to true by default in the next light-my-request release?

Maybe? Anyway it's a long way out as it would end up in Fastify v4.

**Comment by Eomm** [comment]
> I'd be ok to add a `json: true` flag to `inject()` to automatically decode.

It has been always confusing in clients like `got` or `request` between configuring a json paylod for the request and the json parsing for the response.

The status quo I saw is a clearer "responseType: 'json'"

> The Content-Type: header in HTTP responses provides the intended usage of said response bodies.

I think it is now enough since there would be the compression too

**Comment by jsumners** [comment]
> The status quo I saw is a clearer "responseType: 'json'"

One of the big changes from `got@9` to `got@10` was to remove support for `json: true` and require `responseType: 'json'` due to the ambiguity of the former.

> The Content-Type: header in HTTP responses provides the intended usage of the response body.

JSON is mostly simple. The only variant of it that I can think of that would throw a wrench into things is `application/json+json5` (which, is that correct? I don't know. They don't seem to provide a mimetype in their spec -- https://spec.json5.org/). I suppose `application/ld+json` would also be troublesome.

**Comment by mikemaccana** [comment]
> I think it is now enough since there would be the compression too

Do you mean *not* enough? The Content Type shows the intended use of the body, the content encoding shows the compression. Both are sufficient to get a decoded response body, per axios, superagent, etc.
